# Site settings
title: Pranit Bauva (pranitbauva1997)
person_name: Pranit Bauva
person_nickname: pranitbauva1997
email: pranit@bauva.com
mailto: "pranit@bauva.com"
description: Sportsman turned into Programmer and Mathematician
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: pranitbauva1997.github.io
permalink: /:title/

blog_url: https://pranitbauva1997.github.io/
cv_url: http://assets.jimeh.me/jim-myhrberg-cv.pdf
vcard_url: http://assets.jimeh.me/jim-myhrberg.vcf
twitter_username: pranitbauva1997
github_username: pranitbauva1997
# linkedin_username: jimeh
facebook_username: pranit.bauva
# flickr_username: jimeh
# lastfm_username: jimeh

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['vendor/', '_site/', '.sass-cache/', '_local_config.yml', '.bundle/']
