# Site wide configuration

title: Pranit Bauva
locale: en_US
description: Pranit Bauva's personal website
logo: site-logo.png
search: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - octopress-paginate

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  syntax_highlighter: rouge

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Pranit Bauva
  avatar: bio-photo.jpg
  email: pranit@bauva.com
  disqus-shortname: bauva
  twitter: pranitbauva1997
  facebook: pranit.bauva
  github: pranitbauva1997
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: PranitBauva
    analytics: UA-39684817-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

comments: true
